# Generated by Django 3.2.10 on 2022-01-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsmodel',
            old_name='event_name',
            new_name='title',
        ),
    ]
