# Generated by Django 3.2.10 on 2022-01-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_rename_event_name_eventsmodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsmodel',
            old_name='title',
            new_name='event_name',
        ),
    ]
